travis:
  secure:
    BINSTAR_TOKEN: D7BC2+JQyw7VgR5WTNw6rYmy2Rt/W2q+yjzI5HW7XAWciqnynzGOuFL8O2QWwB0UYlHrf0kBO8B2dVk11VxnVFvNYDpJh/czz89ag45/e5Z7q4xPZ0ALBzzEV15e506FPRizZQvDka+A+3erJkqm7nhQ2/q6yAMdCJLmEG3OzmLXyUEdBDJw9ch7edccKcgITnn8BEnWSfWYCdw5P+UasHmPm4ErKBj3rpZuPXMKvMJdtBl+BimBXu2/v0aT1B2TWOCd80cVfPxx3XJQYPBlHujAe2arUCyhybKvQ0YhsnxhWlSTHfdM8iwKUN5xeww7z5xMnaDJLKJqgfWKuUPcjH3SIbjx1KI2E8wIWTXEOrX57zoMNuh7rOOVdLb9SOYilCGnYhPWJDhC23FPsxwMoD3blXH8WsEPDIVAx850AZYW9+yU2WPxkt+U33tgUCebBmb48kPlsz+lVzUYdrNjQmSVqNQG2+mZT9nH1r3fK7ECDzIV2/Iw2Cy8cOELk5+FgfDr37DjpZb4498IGkI8/2S8no7AHTADiV0usY7eXt3hOnECi64g7t9NEEXwuQFggfJJGjjjjiBZjq2cZBW+t261EOk8wQsHYKQJGvcgBk5SLMYtvL13GdysjnNB2Ifm9wdDtwMZyC9GW1vkVVVCfzOorBdFlc8fPZwyx76aOlM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
